import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { I18nextProvider } from "react-i18next";
import i18next from "i18next";
// import en_lang from "../../translations/en.json"
// import ar_lang from "../../translations/ar.json"
import { cookiesLang } from "@/config/config";
import Cookies from "js-cookie";
import { NextIntlClientProvider, useMessages } from "next-intl";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "ARA Technologies MEA",
    description: "Generated by create next app",
};

export default function LocaleLayout({ children, params: { locale } }: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    const messages = useMessages();
    return (
        <html lang={locale}>
            <body suppressHydrationWarning={true}>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    );
}


